### ISSUE TITLE
ToSnake not support  string contains "."

### ISSUE THREAD

**Issue by jzlikewei** [iancoleman/strcase#16]
ToSnake("AwesomeAcitvity.UserID") should be "awesome_acitvity.user_id" but not "awesome_acitvity._user_id"

**Comment by floydspace** [comment]
Hey @jzlikewei, shouldn't it be `awesome_acitvity_user_id`?

**Comment by iancoleman** [comment]
See #17 test which fixes this in `func TestToSnakeWithIgnore(t *testing.T)`

https://github.com/iancoleman/strcase/blob/44067336ae3b42cd97c86be08287cf674b7ca193/snake_test.go#L78

Thanks @jzlikewei
