### ISSUE TITLE
Wrong lower camel case for ID

### ISSUE THREAD

**Issue by aaveidt** [iancoleman/strcase#18]
I've tried lower camel case for `ID` and the result is `iD`.
It's supposed to be `id`

**Comment by iancoleman** [comment]
See https://github.com/iancoleman/strcase/commit/198ca931c72a4aae00d03776eb6dec677e0f23b1

Not a complete solution but one that can be improved into the future.

Unfortunately this hasn't addressed the similar test case in https://github.com/iancoleman/strcase/pull/15/files `{"UserID", "userId"},` but for now this particular issue has been addressed.

Thanks for reporting it.
